name: idv_map_guides
description: "IdentityV AddedPagesNotes maps."
publish_to: 'none'

version: 0.1.0+20260709

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  talker_flutter: ^4.9.2
  talker_bloc_logger: ^4.9.2
  sentry_flutter: ^9.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - maps/lhp/

flutter_intl:
  enabled: true
