name: idv_map_guides
description: "IdentityV CrypticNotes maps guide."
publish_to: 'none'

version: 0.1.0+20260709

environment:
  sdk: ^3.13.2
  flutter: ^3.47.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  sentry_flutter: ^9.27.0
  freezed_annotation: ^3.1.0
  toastification: ^3.2.0
  file_picker: ^12.1.0
  path: ^1.9.1
  messagepack: ^0.2.1
  comparators: ^1.2.0
  cachemesh: ^2.0.0
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.16.0
  freezed: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/maps/the_bringer_of_doom/hard/
    - assets/maps/the_bringer_of_doom/insane/

flutter_intl:
  enabled: true
