name: Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      SENTRY_ORG: ${{ vars.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Integrate Platform
        run: flutter create --platforms web .

      - name: Install Dependencies
        run: flutter pub get

      - name: Generate intl
        run: dart run intl_utils:generate

      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Compile Web Worker
        run: dart compile js "./lib/core_navigator/navigator.web.g.dart" -o "./web/workers/navigator.web.g.dart.js"

      - name: Build Web
        run: flutter build web --release --base-href /${{ github.event.repository.name }}/

      - name: Upload Debug Symbols to Sentry
        run: dart run sentry_dart_plugin
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build/web'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
