name: Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      SENTRY_ORG: ${{ vars.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Cache precomputed assets
        uses: actions/cache@v6
        with:
          path: assets/**/*.precomputed
          key: precomputed-${{ hashFiles('assets/**/*.precomputed') }}
          restore-keys: |
            precomputed-

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Generate codes
        run: |
          flutter create --platforms web .
          flutter pub get
          dart run intl_utils:generate
          dart run build_runner build

      - name: Precompute assets
        run: |
          dart compile exe tool/precompute_navigator.dart -o precompute_navigator && ./precompute_navigator

      - name: Build Web
        run: |
          dart compile wasm "./lib/core_navigator/navigator.web.g.dart" -o "./web/workers/navigator.web.g.dart.wasm"
          flutter build web --release --wasm --base-href /${{ github.event.repository.name }}/

      - name: Upload Debug Symbols to Sentry
        run: dart run sentry_dart_plugin
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build/web'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
